### ISSUE TITLE
Problem Launching

### ISSUE THREAD

**Issue by Rydwxz** [generic-daw/generic-daw#6]
I am using Arch Linux, Pipewire-Jack, X11, Focusrite Clarett+ 2Pre

`cargo run --release` builds successfully on my machine, but the DAW fails to launch with this message: 
```
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp

thread 'main' panicked at generic_daw_core/src/lib.rs:135:10:
called `Result::unwrap()` on an `Err` value: BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_hw_params_set_buffer_size' failed with error 'Invalid argument (22)'" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It looks like the invalid argument is coming from the default config which gives it zero. I see that it tries to load XDG_CONFIG/generic_daw.toml , is there any information on how to prepare that file?

**Comment by edwloef** [comment]
Thanks for the report :)

The default config, which is used if the config file doesn't exist, uses a buffer size of 1024. Not sure why that would fail anywhere tbh, but I should probably make a nicer error screen so everything doesn't break if the output stream can't be created.

The default config looks something like this (change the paths to use your username):
```toml
sample_paths = ["/home/edwin", "/home/edwin/.local/share/Generic Daw"]
clap_paths = ["/home/edwin/.clap", "/usr/lib/clap"]
open_last_project = false
theme = "CatppuccinFrappe"

[input_device]
sample_rate = 44100
buffer_size = 1024

[output_device]
sample_rate = 44100
buffer_size = 1024

[autosave]
enabled = false
interval = 600
```

Could you try messing around with different `buffer_size` values in the `output_device` and see whether that has any effect?

Another thing to note, currently the DAW is set up to use ALSA, not Jack, so maybe it's failing due to a lack of `pipewire-alsa`?
